// Shared content for the homepage and prototypes: the work, placed by how much it draws on
// each of the three questions (structure, cognition, collectives; weights sum
// to 1). The weights are an editorial reading, not a measurement.
window.PROTO_WORKS = [
  {kind: 'paper', year: 2014, venue: 'J. R. Soc. Interface', who: 'G. Petri et al.', title: 'Homological scaffolds of brain functional networks', href: 'https://doi.org/10.1098/rsif.2014.0873', w: [0.66, 0.34, 0], note: 'Topology as a lens on brain activity: what functional networks look like beyond their links.'},
  {kind: 'paper', year: 2019, venue: 'Nature Communications', who: 'I. Iacopini et al.', title: 'Simplicial models of social contagion', href: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6554271/', w: [0.5, 0, 0.5], note: 'Being convinced by a group is not the same as being convinced by its members one at a time.'},
  {kind: 'paper', year: 2020, venue: 'Physics Reports', who: 'F. Battiston et al.', title: 'Networks beyond pairwise interactions: structure and dynamics', href: 'https://arxiv.org/abs/2006.01764', w: [0.74, 0, 0.26], note: 'A field guide to systems whose interactions come in groups.'},
  {kind: 'paper', year: 2021, venue: 'Nature Physics', who: 'G. Petri et al.', title: 'Topological limits to the parallel processing capability of network architectures', href: 'https://doi.org/10.1038/s41567-021-01170-x', w: [0.42, 0.58, 0], note: 'Sharing representations lets a network generalise, and limits how many tasks it can run at once.'},
  {kind: 'paper', year: 2021, venue: 'Nature Physics', who: 'F. Battiston et al.', title: 'The physics of higher-order interactions in complex systems', href: 'https://doi.org/10.1038/s41567-021-01371-4', w: [0.82, 0, 0.18], note: 'What changes in collective dynamics when interactions involve more than two.'},
  {kind: 'paper', year: 2022, venue: 'iScience', who: 'J. Andreas et al.', title: 'Toward understanding the communication in sperm whales', href: 'https://doi.org/10.1016/j.isci.2022.104393', w: [0.1, 0.5, 0.4], note: 'A roadmap for using machine learning to decipher how sperm whales communicate.'},
  {kind: 'paper', year: 2023, venue: 'Communications Biology', who: 'J. S. Pinho et al.', title: 'Social and asocial learning in zebrafish are encoded by a shared brain network that is differentially modulated by local activation', href: 'https://doi.org/10.1038/s42003-023-04999-5', w: [0.25, 0.45, 0.3], note: 'Learning from others and learning alone share one brain network, tuned in different ways.'},
  {kind: 'paper', year: 2023, venue: 'Science', who: 'I. Akinrinade et al.', title: 'Evolutionarily conserved role of oxytocin in social fear contagion in zebrafish', href: 'https://doi.org/10.1126/science.abq5158', w: [0.24, 0.38, 0.38], note: 'Fear passes from fish to fish through oxytocin, a role it also plays in mammals.'},
  {kind: 'paper', year: 2024, venue: 'Proc. CogSci', who: 'A. Brondetta et al.', title: 'On the benefits of heterogeneity in cognitive stability and flexibility for collaborative task switching', href: 'https://escholarship.org/uc/item/6b47b61g', w: [0.15, 0.37, 0.48], note: 'When a team switches tasks together, mixing steady and flexible members can beat a uniform group.'},
  {kind: 'paper', year: 2025, venue: 'Nature Physics', who: 'M. Nurisso et al.', title: 'Higher-order Laplacian renormalization', href: 'https://doi.org/10.1038/s41567-025-02784-1', w: [0.92, 0, 0.08], note: 'Coarse-graining systems with group interactions without losing what the groups do.'},
  {kind: 'paper', year: 2025, venue: 'Nature Communications', who: 'E. Combrisson et al.', title: 'Higher-order and distributed synergistic functional interactions encode information gain in goal-directed learning', href: 'https://doi.org/10.1038/s41467-025-62507-1', w: [0.49, 0.51, 0], note: 'What is learned is carried by synergy among brain regions, in pairs and in groups of three and four.'},
  {kind: 'paper', year: 2025, venue: 'Physical Review Letters', who: 'T. Robiglio et al.', title: 'Synergistic signatures of group mechanisms in higher-order systems', href: 'https://doi.org/10.1103/physrevlett.134.137401', w: [0.62, 0, 0.38], note: 'Group interactions leave a synergistic signature that shows only at the level of the group.'},
  {kind: 'paper', year: 2025, venue: 'eLife', who: 'A. Leitão et al.', title: 'Evidence of social learning across symbolic cultural barriers in sperm whales', href: 'https://doi.org/10.7554/eLife.96362.3', w: [0, 0.32, 0.68], note: 'Sperm whale clans keep what they say apart, and borrow how they say it.'},
  {kind: 'paper', year: 2026, venue: 'ICLR', who: 'M. Nurisso et al.', title: 'Bound by semanticity: universal laws governing the generalization-identification tradeoff', href: 'https://openreview.net/forum?id=ZF0xRAdsuY', w: [0.24, 0.76, 0], note: 'Finite semantic resolution forces a trade-off between generalising and telling things apart.'},
  {kind: 'paper', year: 2026, venue: 'Science', who: 'A. Maalouf et al.', title: 'Cooperation by non-kin during birth underpins sperm whale social complexity', href: 'https://doi.org/10.1126/science.ady9280', w: [0.16, 0, 0.84], note: 'A sperm whale birth, attended and helped by whales that are not kin.'},
  {kind: 'talk', year: 2021, venue: 'CC&B, University of Milan', who: 'Research seminar', title: 'Bridging cognitive control and network theory', href: 'https://www.youtube.com/watch?v=rY8fUhDpSyM', w: [0.34, 0.66, 0], note: 'How the organisation of a network constrains the tasks it can carry out together.'},
  {kind: 'talk', year: 2024, venue: 'IPAM, UCLA', who: 'Research seminar', title: 'Informational and topological signatures of individuality', href: 'https://www.youtube.com/watch?v=5mTLXb069aA', w: [0.55, 0.45, 0], note: 'Reading brain activity as a topological space, and finding what makes each brain identifiable.'},
  {kind: 'conversation', year: 2024, venue: 'Il Post, Sonar (in Italian)', who: 'Podcast, episode 4', title: 'Cose dell’altro mondo', href: 'https://www.ilpost.it/podcasts/sonar/4-cose-dellaltro-mondo', w: [0, 0.27, 0.73], note: 'Project CETI, and the old wish to talk with other animals.'},
  {kind: 'conversation', year: 2025, venue: 'SYNAPSE', who: 'With Shoma Chaudhury', title: 'Can we understand another species?', href: 'https://www.youtube.com/watch?v=DUlJAXc3h0g', w: [0, 0.46, 0.54], note: 'Sperm whale communication, the role of AI, and the ethics of listening in on other lives.'},
  {kind: 'conversation', year: 2026, venue: 'Radio Popolare (in Italian)', who: 'Considera l’armadillo', title: 'Listening to sperm whales', href: 'https://www.radiopopolare.it/puntata/popolare-armadillo/armadillo_24_09_2026_12_48', w: [0, 0.2, 0.8], note: 'Project CETI and the search for meaning in sperm whale communication.'}
];

window.PROTO_QUESTIONS = [
  {name: 'Structure', question: 'When does the whole change the rules?'},
  {name: 'Cognition', question: 'What is the cost of sharing?'},
  {name: 'Collectives', question: 'How do many minds act together?'}
];
